### ISSUE TITLE
Release v0.3.2

### ISSUE THREAD

**Issue by crajcan** [infinyon/http-source-connector#158]
- [x] Check that the version in `crates/http-source/Connector.toml` has been incremented. If needed increment it.
- [x] Tag the intended release with the pattern `vX.Y.Z` matching the version and push it to the repository `git push --tags`. This will start the [Publish Hub](https://github.com/infinyon/http-source-connector/actions/workflows/publish.yaml) wokflow.
- [x] Search [fluvio-website repo](https://github.com/infinyon/fluvio-website/) for documentation examples and update version in examples and documentation of features.
- [x] Check that connector has been published `fluvio hub connector list`

**Comment by crajcan** [comment]
https://github.com/infinyon/fluvio-website/pull/797

**Comment by digikata** [comment]
LGTM
